# This builds & deploy all docker images inside this repo
#
# Following additional ENV-Vars are needed (for GitLab):
# - CI_REGISTRY (via GitLab)
# - CI_REGISTRY_USER (via GitLab)
# - CI_REGISTRY_PASSWORD (via GitLab)
#
# Following additional ENV-Vars are needed (for Docker Hub):
# - DHUB_REGISTRY (via GitLab project settings)
# - DHUB_REGISTRY_USER (via GitLab project settings)
# - DHUB_REGISTRY_PASSWORD (via GitLab project settings)
#
# Following additional ENV-Vars are needed (for GitHub):
# - GHCR_REGISTRY (via GitLab project settings)
# - GHCR_REGISTRY_USER (via GitLab project settings)
# - GHCR_REGISTRY_PASSWORD (via GitLab project settings)
#
# Following vars are set dynamically based on the target path:
# - CI_REGISTRY_IMAGE
# - DHUB_REGISTRY_IMAGE

build_common:
    stage: build
    image:
        name: gcr.io/kaniko-project/executor:v1.9.0-debug
        entrypoint: [""]
    parallel:
        matrix:
        - IMAGE:
            - alpine-deploy
            - alpine-php-doxygen
            - debian-inotifywait
            - debian-pterodactyl
          REPOSITORY:
            - github-ghcr
            - gitlab-ci
            - docker-hub
    script:
        - mkdir -p /kaniko/.docker
        # Adding both repository credentials, as this job may run for both
        - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}, \"$DHUB_REGISTRY\":{\"username\":\"$DHUB_REGISTRY_USER\",\"password\":\"$DHUB_REGISTRY_PASSWORD\"}, \"$GHCR_REGISTRY\":{\"username\":\"$GHCR_REGISTRY_USER\",\"password\":\"$GHCR_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
        - if [[ "$REPOSITORY" == "gitlab-ci" ]]; then export REGISTRY_TARGET=$CI_REGISTRY_IMAGE; elif [[ "$REPOSITORY" == "github-ghcr" ]]; then export REGISTRY_TARGET=$GHCR_REGISTRY_IMAGE; else export REGISTRY_TARGET=$DHUB_REGISTRY_IMAGE; fi
        - /kaniko/executor --cleanup --context $CI_PROJECT_DIR/$IMAGE --destination $REGISTRY_TARGET/$IMAGE:latest

build_alpine_php_mysql:
    stage: build
    image:
        name: gcr.io/kaniko-project/executor:v1.9.0-debug
        entrypoint: [""]
    parallel:
        matrix:
        - VERSION:
            - "7.4"
            - "8.1"
          REPOSITORY:
            - github-ghcr
            - gitlab-ci
            - docker-hub
    script:
        - mkdir -p /kaniko/.docker
        # Adding both repository credentials, as this job may run for both
        - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}, \"$DHUB_REGISTRY\":{\"username\":\"$DHUB_REGISTRY_USER\",\"password\":\"$DHUB_REGISTRY_PASSWORD\"}, \"$GHCR_REGISTRY\":{\"username\":\"$GHCR_REGISTRY_USER\",\"password\":\"$GHCR_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
        - if [[ "$REPOSITORY" == "gitlab-ci" ]]; then export REGISTRY_TARGET=$CI_REGISTRY_IMAGE; elif [[ "$REPOSITORY" == "github-ghcr" ]]; then export REGISTRY_TARGET=$GHCR_REGISTRY_IMAGE; else export REGISTRY_TARGET=$DHUB_REGISTRY_IMAGE; fi
        - /kaniko/executor --cleanup --context $CI_PROJECT_DIR/apache-php-mysql --destination $REGISTRY_TARGET/apache-php-mysql:$VERSION --build-arg FROM_PHP_VERSION=$VERSION