# This builds & deploy all docker images inside this repo
#
# Following additional ENV-Vars are needed (for GitLab):
# - CI_REGISTRY (via GitLab)
# - CI_REGISTRY_USER (via GitLab)
# - CI_REGISTRY_PASSWORD (via GitLab)
#
# Following additional ENV-Vars are needed (for Docker Hub):
# - DHUB_REGISTRY (via GitLab project settings)
# - DHUB_REGISTRY_USER (via GitLab project settings)
# - DHUB_REGISTRY_PASSWORD (via GitLab project settings)
#
# Following vars are set dynamically based on the target path:
# - CI_REGISTRY_IMAGE
# - DHUB_REGISTRY_IMAGE

gitlab-ci:
    stage: build
    image:
        name: gcr.io/kaniko-project/executor:debug
        entrypoint: [""]
    script:
        - mkdir -p /kaniko/.docker
        - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
        - /kaniko/executor --cleanup --context $CI_PROJECT_DIR/alpine-deploy --destination $CI_REGISTRY_IMAGE/alpine-deploy:latest
        - /kaniko/executor --cleanup --context $CI_PROJECT_DIR/alpine-php-doxygen --destination $CI_REGISTRY_IMAGE/alpine-php-doxygen:latest
        - /kaniko/executor --cleanup --context $CI_PROJECT_DIR/apache-php-mysql --destination $CI_REGISTRY_IMAGE/apache-php-mysql:8.1 --build-arg FROM_PHP_VERSION=8.1
        - /kaniko/executor --cleanup --context $CI_PROJECT_DIR/apache-php-mysql --destination $CI_REGISTRY_IMAGE/apache-php-mysql:7.4 --build-arg FROM_PHP_VERSION=7.4
        - /kaniko/executor --cleanup --context $CI_PROJECT_DIR/debian-inotifywait --destination $CI_REGISTRY_IMAGE/debian-inotifywait:latest
        - /kaniko/executor --cleanup --context $CI_PROJECT_DIR/debian-pterodactyl --destination $CI_REGISTRY_IMAGE/debian-pterodactyl:latest
        
docker-hub:
    stage: build
    image:
        name: gcr.io/kaniko-project/executor:debug
        entrypoint: [""]
    script:
        - mkdir -p /kaniko/.docker
        - echo "{\"auths\":{\"$DHUB_REGISTRY\":{\"username\":\"$DHUB_REGISTRY_USER\",\"password\":\"$DHUB_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
        - /kaniko/executor --cleanup --context $CI_PROJECT_DIR/alpine-deploy --destination $DHUB_REGISTRY_IMAGE/alpine-deploy:latest
        - /kaniko/executor --cleanup --context $CI_PROJECT_DIR/alpine-php-doxygen --destination $DHUB_REGISTRY_IMAGE/alpine-php-doxygen:latest
        - /kaniko/executor --cleanup --context $CI_PROJECT_DIR/apache-php-mysql --destination $DHUB_REGISTRY_IMAGE/apache-php-mysql:8.1 --build-arg FROM_PHP_VERSION=8.1
        - /kaniko/executor --cleanup --context $CI_PROJECT_DIR/apache-php-mysql --destination $DHUB_REGISTRY_IMAGE/apache-php-mysql:7.4 --build-arg FROM_PHP_VERSION=7.4
        - /kaniko/executor --cleanup --context $CI_PROJECT_DIR/debian-inotifywait --destination $DHUB_REGISTRY_IMAGE/debian-inotifywait:latest
        - /kaniko/executor --cleanup --context $CI_PROJECT_DIR/debian-pterodactyl --destination $DHUB_REGISTRY_IMAGE/debian-pterodactyl:latest
